### ISSUE TITLE
沃邮箱报错

### ISSUE THREAD

**Issue by xiaohuaming** [Yiov/wool#12]
【微信_沃邮箱---登录】: API查询请求失败
"Hostname/IP does not match certificate's altnames: Host: nyan.mail.wo.cn. is not in the cert's altnames: DNS:womail.richpush.cn"

**Comment by Yiov** [comment]
沃邮箱公众号里的系统又升级了...等吧

**Comment by xiaohuaming** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiaohuaming** [comment]
thanks
