### ISSUE TITLE
快手极速版

### ISSUE THREAD

**Issue by xiaohuaming** [Yiov/wool#14]
现在打开快手极速版看不到入口了，也无法自动提现，不知道怎么搞，有没有链接能快速进去

**Comment by Yiov** [comment]
app右上角三横 > 积分换好礼

**Comment by xiaohuaming** [comment]
我的iphone打开app都没有这个。。。

**Comment by Yiov** [comment]
设置-反馈与帮助-搜索：积分

1.赚积分活动如何提现

2.赚积分红包消失，如何提现

这两个问题下均有提现入口，你可以试试

**Comment by xiaohuaming** [comment]
好的。我去看下，感谢答复
