### ISSUE TITLE
快手普通版设置好后点运行什么日志都没有，就像没设置环境变量一样

### ISSUE THREAD

**Issue by ForeverDuke** [Yiov/wool#22]
快手普通版设置好后点运行什么日志都没有，就像没设置环境变量一样

**Comment by Yiov** [comment]
那就检查一下环境变量嘛，是ksco o kie不是ksjsbCookie

**Comment by Yiov** [comment]
那就检查一下环境变量嘛，是ksCookie不是ksjsbCookie

**Comment by ForeverDuke** [comment]
> 那就检查一下环境变量嘛，是ksCookie不是ksjsbCookie

环境变量检查过
在配置文件里面添加的
也尝试过直接在环境变量里面设置
但是都没有反应

**Comment by ForeverDuke** [comment]
环境变量设置没有问题，从原作者那边重新拉脚本，可以正常运行；
您这边的依然日志空空如也

另外 我Cookie并不能通用，需要重新抓，不知道是不是个例

**Comment by Yiov** [comment]
那应该就是个例，我跑了3个是正常的，原作者今天上午也进行了更新，总之解决就好了
