### ISSUE TITLE
快手普通版今天提示违规操作无法提现了

### ISSUE THREAD

**Issue by ForeverDuke** [Yiov/wool#29]

**Comment by Yiov** [comment]
没有打开快手刷过吧，稍微活跃点，还有定时可以自己改改。手动提现试试，在右上角三横-更多-我的钱包-天降红包提现

**Comment by ForeverDuke** [comment]
> 没有打开快手刷过吧，稍微活跃点，还有定时可以自己改改。手动提现试试，在右上角三横-更多-我的钱包-天降红包提现

刚开始刷的时候手动刷过

定时倒是改过的
 
现在只能手动刷一阵子试试看了  不知道能不能解封

**Comment by Yiov** [comment]
我也中招了 就刚刚 极速版…

**Comment by Yiov** [comment]
极速版在积分换好礼那里手动体现就好了

**Comment by ForeverDuke** [comment]
> 极速版在积分换好礼那里手动体现就好了

今天提过现了，过12点手动试试

**Comment by ForeverDuke** [comment]
> 极速版在积分换好礼那里手动体现就好了

嗯 手动可以提现
